apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: release-name-nginx
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: nginx
          image: "nginx:alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          # This (and the volumes section below) mount the config map as a volume.
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: wwwdata-volume
      volumes:
        - name: wwwdata-volume
          configMap:
            name: release-name-nginx
