apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: release-name
  name: release-name-nginx
spec:
  type: "ClusterIP"
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: release-name
